#!/bin/bash

if [ "$(id -u)" -ne 0 ]; then
    echo "Please run this script with root privileges."
    exit 1
fi

mkdir /usr/share/ihaahi/S-TOR
mv stor.py /usr/share/ihaahi/S-TOR/


mv stor /usr/local/bin/
chmod +x /usr/local/bin/stor

echo stor install successfully
echo type stor in target directory that you want to access via .onion link
