#!/bin/bash

if [ "$(id -u)" -ne 0 ]; then
    echo "Please run this script with root privileges."
    exit 1
fi
directory="/usr/share/ihaahi"
if [ -d "$directory" ]; then
    #nothing
else
    mkdir /usr/share/ihaahi
fi

mkdir /usr/share/ihaahi/S-Tor
mv stor.py /usr/share/ihaahi/S-Tor/


mv stor /usr/local/bin/
chmod +x /usr/local/bin/stor

echo stor install successfully
echo Type stor in target directory that you want to access via .onion link
